services:
  api-gateway:
    user: root
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${API_PORT:-3000}:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - DEFAULT_ADMIN_USER=${DEFAULT_ADMIN_USER}
      - DEFAULT_ADMIN_PASS=${DEFAULT_ADMIN_PASS}
      - DOCKER_SOCKET=/var/run/docker.sock
      - MASTER_KEY_HEX=${MASTER_KEY_HEX}
      - PAYSTACK_SECRET_KEY=${PAYSTACK_SECRET_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
#      - DB_URI=postgres://whatsapp:whatsapp@postgres:5432/whatsapp?sslmode=disable

    networks:
      - hapaniwapi-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-whatsapp}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-whatsapp}
      - POSTGRES_DB=${POSTGRES_DB:-whatsapp}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5440}:5432"
    networks:
      - hapaniwapi-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-whatsapp}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  hapaniwapi-net:

volumes:
  postgres_data:
