services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    ports:
      - "${API_PORT:-3000}:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - app_data:/app/data
      - app_logs:/app/logs
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - DEFAULT_ADMIN_USER=${DEFAULT_ADMIN_USER}
      - DEFAULT_ADMIN_PASS=${DEFAULT_ADMIN_PASS}
      - DOCKER_SOCKET=/var/run/docker.sock
      - MASTER_KEY_HEX=${MASTER_KEY_HEX}
      - PAYSTACK_SECRET_KEY=${PAYSTACK_SECRET_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - SERVER_URL=${SERVER_URL}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}        # optional if unauthenticated SMTP
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_SECURE=${SMTP_SECURE}        # "true" for TLS (port 465)
      - SMTP_FROM_INFO=${SMTP_FROM_INFO}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - START_RABBITMQ_CONSUMER=true
      - START_RABBITMQ_PRODUCER=true
#      - DB_URI=postgres://whatsapp:whatsapp@postgres:5432/whatsapp?sslmode=disable
    networks:
      - hapaniwapi-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    depends_on:
      - postgres
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    container_name: wapflow_rabbitmq
    ports:
      - "5675:5672"   # AMQP protocol
      - "15675:15672" # Management UI
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - hapaniwapi-net
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  consumer:
    build: .
    container_name: consumer
    restart: unless-stopped
    networks:
      - hapaniwapi-net
    command: node dist/rabbitmq/consumer.js
    user: root
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}        # optional if unauthenticated SMTP
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_SECURE=${SMTP_SECURE}        # "true" for TLS (port 465)
      - SMTP_FROM_INFO=${SMTP_FROM_INFO}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - QUEUE_NAME=${QUEUE_NAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - app_data:/app/data
      - app_logs:/app/logs

  producer:
    build: .
    container_name: producer
    restart: unless-stopped
    networks:
      - hapaniwapi-net
    command: node dist/rabbitmq/producer.js
    depends_on:
      rabbitmq:
        condition: service_healthy
      consumer:
        condition: service_started
    environment:
      - RABBITMQ_URL=${RABBITMQ_URL}
      - QUEUE_NAME=${QUEUE_NAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - app_data:/app/data
      - app_logs:/app/logs

  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-whatsapp}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-whatsapp}
      - POSTGRES_DB=${POSTGRES_DB:-whatsapp}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5440}:5432"
    networks:
      - hapaniwapi-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-whatsapp}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  hapaniwapi-net:

volumes:
  postgres_data:
  rabbitmq_data:
  app_data:
  app_logs:

